### ISSUE TITLE
minecraft profiles

### ISSUE THREAD

**Issue by kalorichen** [thesilvercraft/SilverBot#17]
make minecraft profiles with silverbot

**Comment by Silverdimond** [comment]
Can you be a little more specific?
Do you mean to create a minecraft account or something different because i think mojang does not allow bots to create accounts?

**Comment by kalorichen** [comment]
make the bot like name mc so it can show account for exaple if i type sd!mc account <account:name>
it shows the account like the fortnite command

**Comment by Silverdimond** [comment]
![image](https://user-images.githubusercontent.com/46320280/109649149-c7d81680-7b5b-11eb-86f9-ae073acaddd6.png)
something like this?
