### ISSUE TITLE
Anime

### ISSUE THREAD

**Issue by Wbubbler** [thesilvercraft/SilverBot#205]

**Comment by Silverdimond** [comment]
what

**Comment by MDproductions-dev** [comment]
add anime

**Comment by Silverdimond** [comment]
how

**Comment by MDproductions-dev** [comment]
just add it

**Comment by Silverdimond** [comment]
![image](https://user-images.githubusercontent.com/46320280/125099325-31eb6400-e0d8-11eb-9859-3caecbe22bec.png)
according to the cmpc bible you hate anime
and the cmpc bible never lies

**Comment by MDproductions-dev** [comment]
oh yeah but bub likes anime

**Comment by Silverdimond** [comment]
true

**Comment by Silverdimond** [comment]
@Wbubbler what anime do i add?

**Comment by Wbubbler** [comment]
uhm
Pokemon i guess

**Comment by Oscie57** [comment]
add dobutsu no mori or lwa or smth pokemon isnt thatgood

**Comment by Silverdimond** [comment]
I still have no idea how I would add the anime in the bot, or the bots code.
Any suggestions?

**Comment by Wbubbler** [comment]
Pokemon is best
cant change my mind

**Comment by Oscie57** [comment]
make the bot send audio clips and video clips from them randomly in every server

**Comment by Wbubbler** [comment]
And make that these audio clips and video clips have the language which the server is set to if available

**Comment by Silverdimond** [comment]
just randomly at 00:00
silverbot Today at 00:00
<insert 'i wanna be the very best'  pokemon theme>

**Comment by Silverdimond** [comment]
eventually when i finish custom prefixes i might add anime WHAT COULD GO WRONG

**Comment by MDproductions-dev** [comment]
just add a command that sends anime picture

**Comment by Silverdimond** [comment]
@Wbubbler you do it

**Comment by Wbubbler** [comment]
no

**Comment by Silverdimond** [comment]
i am too busy watching anime

**Comment by Wbubbler** [comment]
SilverDiamond will do this

**Comment by Silverdimond** [comment]
thats not how it works

**Comment by Wbubbler** [comment]
It is

**Comment by Silverdimond** [comment]
![image](https://user-images.githubusercontent.com/46320280/126029515-f90bdfa1-e5f9-47c7-b170-5d59ab49511f.png)
![image](https://user-images.githubusercontent.com/46320280/126029520-f5e57b8a-5b42-4f7a-a556-97199d3354a7.png)
so @MDproductions-dev listed two packages for different languages which i believe both access the same api located at https://anime-api.hisoka17.repl.co/
still not sure what i am supposed to do with this info

**Comment by Silverdimond** [comment]
![image](https://user-images.githubusercontent.com/46320280/126030544-5329e027-8e10-4d4c-b92b-f1c854f034a8.png)
implemented something, uh bub is happy now, ill go sleep now
